name: test curl on windows

on: 
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check OS on Windows
        if: runner.os == 'Windows'
        run: |
            curl --version
            winget -v
