name: echo os ver

on: 
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - id: record-begin-time
        uses: ali50m/actions/new-record-begin-time@main
        
      - name: Check OS on Linux
        if: runner.os == 'Linux'
        run: |
            echo "This is Linux"
            echo ${{steps.record-begin-time.outputs.now}}
      - name: Check OS on Windows
        if: runner.os == 'Windows'
        run: |
            echo "This is Windows"
            echo ${{steps.record-begin-time.outputs.now}}
      - name: Check OS on Mac
        if: runner.os == 'macOS'
        run: |
            echo "This is macOS"
            echo ${{steps.record-begin-time.outputs.now}}
